---
deployment:
  tasks:
    - export DEPLOYPATH=/home/medicoweb/public_html/teacher-traking/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/storage/uploads
    - /bin/mkdir -p $DEPLOYPATH/storage/logs
    - /usr/bin/rsync -av --exclude=".git" --exclude=".cpanel.yml" --exclude=".gitignore" --exclude=".env" --exclude="storage/uploads/" --exclude="storage/logs/" --exclude="*.log" --exclude="deploy-cpanel.zip" ./ $DEPLOYPATH
